# via https://www.zabbix.com/documentation/2.0/jp/manual/installation/install_from_packages
- name: install libselinux-python for selinux
  yum: name=libselinux-python state=present

- name: zabbix rpm install
  yum: name=http://repo.zabbix.com/zabbix/2.2/rhel/6/x86_64/zabbix-release-2.2-1.el6.noarch.rpm state=present

- name: zabbix-agent yum install
  yum: name=zabbix-agent state=present

- name: zabbix sender rpm install
  yum: name=http://repo.zabbix.com/zabbix/2.2/rhel/6/x86_64/zabbix-sender-2.2.9-1.el6.x86_64.rpm

- name: zabbix-sender yum install
  yum: name=zabbix-sender state=present



