# via https://www.zabbix.com/documentation/2.0/jp/manual/installation/install_from_packages

- name: zabbix rpm install
  yum: name=http://repo.zabbix.com/zabbix/2.2/rhel/6/x86_64/zabbix-release-2.2-1.el6.noarch.rpm state=present

- name: zabbix-server-mysql yum install
  yum: name=zabbix-server-mysql state=present
  
- name: zabbix-web-mysql yum install
  yum: name=zabbix-web-mysql state=present

- name: zabbix-web-japanese yum install
  yum: name=zabbix-web-japanese state=present


#  yum: name={{ item }} state=installed
#  with_items:
#    - zabbix-server-mysql
#    - zabbix-web-mysql
#    - zabbix-web-japanese


# zabbix 用 DB の作成
#- name: Create database
#  mysql_db: db=zabbix state=present encoding=utf8

# zabbix 用 DB ユーザーの作成
#- name: Create database user
#  mysql_user: >
#    name=zuser
#    password="password"
#    priv=zabbix.*:ALL
#    state=present
